default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  host: localhost

test:
  <<: *default
  database: user_user_sequence_test

development:
  <<: *default
  database: user_user_sequence_development

staging:
  <<: *default
  database: user_user_sequence_staging

production:
  <<: *default
  database: user_user_sequence_production
